### ISSUE TITLE
Word Example Document not working

### ISSUE THREAD

**Issue by dpafumi** [zorantica/plsql-word#1]
Thanks for this great idea and code.
I'm having an issue using your example code.
When I tried to open it in Word, I get:
"We're sorry. We can't open ZT_Word example because we found a problem with its contents..
Details: 
illegal xml character.
Location: Part: /word/numbering.xml, Line 8, Column 22.

Any ideas please?
Thanks!

**Comment by jtsoya539** [comment]
Hi @dpafumi 
I had the same error, so I replaced these characters in examples.sql:
`'€'
'·'`

I think the error is related to Database charset

**Comment by zorantica** [comment]
Hi @dpafumi and @jtsoya539 
I fixed the example.sql few month ago and replaced EUR UTF-8 sign with fixed "EUR" text. 
I noticed exactly the same problem... and like @jtsoya539 mentioned it was linked to file and database encoding.
