### ISSUE TITLE
word example worked fine, but Arabic language not supported

### ISSUE THREAD

**Issue by aelabediug** [zorantica/plsql-word#2]
hi zoran, 
thank you about your plsql-word. 

I do some changes to run your example , and the result is fun. 
I replace:
    --for testing purposes we save the document in directory
    /*ZT_WORD.p_save_file(
        p_document => lbDokument,
        p_folder => 'E_SHARED',
        p_file_name => 'ZT_WORD example.docx');*/
--By: 
   
   SYS.HTP.INIT;  
   owa_util.mime_header('application/octet-stream', false);  
   htp.p('Content-Length: ' || dbms_lob.getlength(lbDokument));   
   htp.p('Content-Disposition: attachment; filename="ZT_WORD example.DOCX"');   
   owa_util.http_header_close();   
   wpg_docload.download_file(lbDokument);

But, when I write any arabic language in your example, the word text cannot opened. 
may you solve it! 

thanks.

**Comment by zorantica** [comment]
Hi @aelabediug,

what is a character encoding of Your database?
If Your database encoding is not AL32UTF8 and Your strings contain special characters (and in You case of Arabic language it certainly has) then You should convert string to UTF-8 before calling procedures with text parameters (for example parameter p_text in procedure p_add_text). Easiest way is to use Oracle CONVERT function.

I don't know how to write Arabic properly... but I installed Arabic language on my computer, wrote few test words as an example and generated document. 

![image](https://user-images.githubusercontent.com/33637578/114317958-e17d5e00-9b0a-11eb-8a71-3967080bd46d.png)

My database is AL32UTF8. Generated document was correct:

![image](https://user-images.githubusercontent.com/33637578/114317896-a3803a00-9b0a-11eb-8836-eaf7d5288865.png)

Please, let me know if this solution helps.

**Comment by aelabediug** [comment]
Thank you very muck Mr. zoran. 
It's work. 

ZT_WORD.p_add_text(
        p_doc_id => lnDok,
        p_paragraph_id => lnParagraph,
        p_text => CONVERT( 'of bold text اللغة العربية الحمد لله', 'AL32UTF8' , 'AR8MSWIN1256'),
        p_font => ZT_WORD.f_font(p_bold => true)
        );

**Comment by zorantica** [comment]
Fantastic!
I'm glad it worked!

If you encounter any other issue don't hesitate to contact me or open another issue here.
