### ISSUE TITLE
Inserting in a table cell the character "&" results in a corrupted docx

### ISSUE THREAD

**Issue by paolopangrazi** [zorantica/plsql-word#7]
When putting an ampersand "&" or the relative ascii chr code in any table cell, the docx is generated but cannot be opened. Possible resolution: I think the character must be somehow "escaped" in the xml data or translated.

**Comment by zorantica** [comment]
Fixed! Please pull latest version of package and try.

**Comment by paolopangrazi** [comment]
Just tested it, it works! Thanks a lot! Thumbs up!
